# Data Analysis for PAPI detection and classification dataset

## Imports

In [4]:
# Imports
import pandas as pd
import os
import shutil
import exifread
import numpy as np
import random

## File path sorting/matching

In [9]:
# Defining paths for data files
data_master_path = "../../Data/PROJECT1-PAPI/"
data_files = os.listdir(data_master_path)

In [10]:
print("Data files available:")
for file in data_files:
    print(f" - {file}")

Data files available:
 - DJI_202604281910_010_UgCS
 - DJI_202604281946_011_700
 - DJI_202604281946_012_600
 - DJI_202604281946_013_800
 - DJI_202604281946_014_1000
 - DJI_202604290007_019_300mRwy06night
 - DJI_202604290007_020_300mrway06nightdown
 - DJI_202604290007_021_400mrwy06night
 - DJI_202604290007_022_400mrwy06dwnnighf
 - DJI_202604290007_023_500mrwy06night
 - DJI_202604291300_031_day2700mup
 - DJI_202604291300_032_day2700mdwnzoom
 - DJI_202604291357_034_600day2up
 - DJI_202604291550_035_UgCS-vertical600mEDNYPAPIHowest
 - DJI_202604291550_036_400mday2up
 - DJI_202604291738_037_500mday2v2up
 - DJI_202604291738_038_500day2v2dwnzoom
 - DJI_202604291738_039_400mday2up
 - DJI_202604291738_040_400day2dwnleftoffset
 - DJI_202604291738_041_300mday2up
 - DJI_202604291738_042_300mday2dwntiltedzoom
 - PAPI_Coords_Fred_DE.xlsx

In [4]:
# Load excel file into dataframe
excel_path = os.path.join(data_master_path, "PAPI_Coords_Fred_DE.xlsx")
PAPI_06_df = pd.read_excel(excel_path, header=1, nrows=4)
PAPI_06_df.head(4)

  Bezeichnung  Punktnummer  longitude   latitude
0     PAPI 06            1   9.504007  47.668810
1     PAPI 06            2   9.503948  47.668881
2     PAPI 06            3   9.503888  47.668951
3     PAPI 06            4   9.503828  47.669021

In [5]:
PAPI_24_df = pd.read_excel(excel_path, header=9, nrows=4)
PAPI_24_df.head(4)

  Bezeichnung  Punktnummer  longitude   latitude
0     PAPI 24            1   9.518154  47.673521
1     PAPI 24            2   9.518214  47.673450
2     PAPI 24            3   9.518274  47.673380
3     PAPI 24            4   9.518333  47.673309

In [11]:
# Remove excel file from data_files
data_files.remove("PAPI_Coords_Fred_DE.xlsx")

In [12]:
# Split folders based on name to new folders matching the PAPI lights in the image
PAPI_06_data = []
PAPI_24_data = []
for filename in data_files:
    if "y06" in filename:
        PAPI_06_data.append(filename)
    else:
        PAPI_24_data.append(filename)

In [13]:
print(f"PAPI 06 datafiles: {PAPI_06_data}")
print(f"PAPI 24 datafiles: {PAPI_24_data}")

PAPI 06 datafiles: ['DJI_202604290007_019_300mRwy06night', 'DJI_202604290007_020_300mrway06nightdown', 'DJI_202604290007_021_400mrwy06night', 'DJI_202604290007_022_400mrwy06dwnnighf', 'DJI_202604290007_023_500mrwy06night']
PAPI 24 datafiles: ['DJI_202604281910_010_UgCS', 'DJI_202604281946_011_700', 'DJI_202604281946_012_600', 'DJI_202604281946_013_800', 'DJI_202604281946_014_1000', 'DJI_202604291300_031_day2700mup', 'DJI_202604291300_032_day2700mdwnzoom', 'DJI_202604291357_034_600day2up', 'DJI_202604291550_035_UgCS-vertical600mEDNYPAPIHowest', 'DJI_202604291550_036_400mday2up', 'DJI_202604291738_037_500mday2v2up', 'DJI_202604291738_038_500day2v2dwnzoom', 'DJI_202604291738_039_400mday2up', 'DJI_202604291738_040_400day2dwnleftoffset', 'DJI_202604291738_041_300mday2up', 'DJI_202604291738_042_300mday2dwntiltedzoom']

In [14]:
dest_root_06 = "./dataset/PAPI_06"
os.makedirs(dest_root_06, exist_ok=True)

for file_path in PAPI_06_data:
    src = os.path.join(data_master_path, file_path)
    dst = os.path.join(dest_root_06, os.path.basename(file_path))
    
    shutil.copytree(src, dst, dirs_exist_ok=True)

In [15]:
dest_root_24 = "./dataset/PAPI_24"
os.makedirs(dest_root_24, exist_ok=True)

for file_path in PAPI_24_data:
    src = os.path.join(data_master_path, file_path)
    dst = os.path.join(dest_root_24, os.path.basename(file_path))
    
    shutil.copytree(src, dst, dirs_exist_ok=True)

## Metadata analysis

In [16]:
img_path = "dataset\PAPI_06\DJI_202604290007_019_300mRwy06night\DJI_20260429002101_0001_V.JPG"
def read_all_metadata(image_path):
    with open(image_path, "rb") as f:
        tags = exifread.process_file(f, details=True)

    for tag in tags:
        print(f"{tag}: {tags[tag]}")
read_all_metadata(img_path)

Image ImageDescription: default
Image Make: DJI
Image Model: M4E
Image Orientation: Horizontal (normal)
Image XResolution: 72
Image YResolution: 72
Image ResolutionUnit: Pixels/Inch
Image Software: 10.00.14.82
Image DateTime: 2026:04:29 00:21:01
Image YCbCrPositioning: Co-sited
Image ExifOffset: 260
GPS GPSVersionID: [2, 3, 0, 0]
GPS GPSLatitudeRef: N
GPS GPSLatitude: [47, 40, 29479/10000]
GPS GPSLongitudeRef: E
GPS GPSLongitude: [9, 30, 3263/2000]
GPS GPSAltitudeRef: 0
GPS GPSAltitude: 465147/1000
GPS GPSStatus: A
GPS GPSMapDatum: WGS-84
Image GPSInfo: 758
Image XPComment: [48, 0, 46, 0, 57, 0, 46, 0, 49, 0, 52, 0, 50, 0, 0, 0, 0, 0, 0, 0, ... ]
Image XPKeywords: [115, 0, 105, 0, 110, 0, 103, 0, 108, 0, 101, 0]
Thumbnail Compression: JPEG
Thumbnail XResolution: 72
Thumbnail YResolution: 72
Thumbnail ResolutionUnit: Pixels/Inch
Thumbnail JPEGInterchangeFormat: 6808
Thumbnail JPEGInterchangeFormatLength: 1925
EXIF ExposureTime: 1/80
EXIF FNumber: 14/5
EXIF ExposureProgram: Manual
EXIF ISOSpeedRatings: 100
EXIF SensitivityType: Recommended Exposure Index
EXIF RecommendedExposureIndex: 100
EXIF ExifVersion: 0230
EXIF DateTimeOriginal: 2026:04:29 00:21:01
EXIF DateTimeDigitized: 2026:04:29 00:21:01
EXIF ComponentsConfiguration: YCbCr
EXIF ShutterSpeedValue: 632193/100000
EXIF ApertureValue: 297/100
EXIF ExposureBiasValue: -3
EXIF MaxApertureValue: 297/100
EXIF SubjectDistance: 0
EXIF MeteringMode: Average
EXIF LightSource: Daylight
EXIF Flash: Flash did not fire
EXIF FocalLength: 1229/100
EXIF MakerNote: [6, 0, 1, 16, 1, 0, 20, 0, 0, 0, 152, 5, 0, 0, 2, 16, 7, 0, 233, 20, ... ]
EXIF FlashPixVersion: 0100
EXIF ColorSpace: sRGB
EXIF ExifImageWidth: 5280
EXIF ExifImageLength: 3956
Interoperability InteroperabilityIndex: R98
Interoperability InteroperabilityVersion: [48, 49, 48, 48]
EXIF InteroperabilityOffset: 872
EXIF FileSource: Digital Camera
EXIF SceneType: Directly Photographed
EXIF CustomRendered: Normal
EXIF ExposureMode: Manual Exposure
EXIF WhiteBalance: Auto
EXIF DigitalZoomRatio: 1
EXIF FocalLengthIn35mmFilm: 24
EXIF SceneCaptureType: Standard
EXIF GainControl: None
EXIF Contrast: Normal
EXIF Saturation: Normal
EXIF Sharpness: Normal
EXIF DeviceSettingDescription: [0, 0, 0, 0]
EXIF BodySerialNumber: 1581F7FVC252500C11EY
EXIF LensSpecification: [24, 24, 14/5, 11]
EXIF Tag 0xC614: DJI M4E
MakerNote Tag 0x1001: [63, 50, 39, 60, 38, 25, 4, 12, 8, 5, 2, 250, 2, 6, 0, 11, 13, 35, 32, 66]
MakerNote Tag 0x1002: []
MakerNote Tag 0x1003: 240
MakerNote Tag 0x1004: (1.0,)
MakerNote Tag 0x1005: 0
MakerNote Tag 0x1006: 0
JPEGThumbnail: b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x02\x00\x00\x01\x00\x01\x00\x00\xff\xdb\x00C\x00\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\xff\xdb\x00C\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\xff\xc0\x00\x11\x08\x00x\x00\xa0\x03\x01"\x00\x02\x11\x01\x03\x11\x01\xff\xc4\x00\x1f\x00\x00\x01\x05\x01\x01\x01\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x01\x02\x03\x04\x05\x06\x07\x08\t\n\x0b\xff\xc4\x00\xb5\x10\x00\x02\x01\x03\x03\x02\x04\x03\x05\x05\x04\x04\x00\x00\x01}\x01\x02\x03\x00\x04\x11\x05\x12!1A\x06\x13Qa\x07"q\x142\x81\x91\xa1\x08#B\xb1\xc1\x15R\xd1\xf0$3br\x82\t\n\x16\x17\x18\x19\x1a%&\'()*456789:CDEFGHIJSTUVWXYZcdefghijstuvwxyz\x83\x84\x85\x86\x87\x88\x89\x8a\x92\x93\x94\x95\x96\x97\x98\x99\x9a\xa2\xa3\xa4\xa5\xa6\xa7\xa8\xa9\xaa\xb2\xb3\xb4\xb5\xb6\xb7\xb8\xb9\xba\xc2\xc3\xc4\xc5\xc6\xc7\xc8\xc9\xca\xd2\xd3\xd4\xd5\xd6\xd7\xd8\xd9\xda\xe1\xe2\xe3\xe4\xe5\xe6\xe7\xe8\xe9\xea\xf1\xf2\xf3\xf4\xf5\xf6\xf7\xf8\xf9\xfa\xff\xc4\x00\x1f\x01\x00\x03\x01\x01\x01\x01\x01\x01\x01\x01\x01\x00\x00\x00\x00\x00\x00\x01\x02\x03\x04\x05\x06\x07\x08\t\n\x0b\xff\xc4\x00\xb5\x11\x00\x02\x01\x02\x04\x04\x03\x04\x07\x05\x04\x04\x00\x01\x02w\x00\x01\x02\x03\x11\x04\x05!1\x06\x12AQ\x07aq\x13"2\x81\x08\x14B\x91\xa1\xb1\xc1\t#3R\xf0\x15br\xd1\n\x16$4\xe1%\xf1\x17\x18\x19\x1a&\'()*56789:CDEFGHIJSTUVWXYZcdefghijstuvwxyz\x82\x83\x84\x85\x86\x87\x88\x89\x8a\x92\x93\x94\x95\x96\x97\x98\x99\x9a\xa2\xa3\xa4\xa5\xa6\xa7\xa8\xa9\xaa\xb2\xb3\xb4\xb5\xb6\xb7\xb8\xb9\xba\xc2\xc3\xc4\xc5\xc6\xc7\xc8\xc9\xca\xd2\xd3\xd4\xd5\xd6\xd7\xd8\xd9\xda\xe2\xe3\xe4\xe5\xe6\xe7\xe8\xe9\xea\xf2\xf3\xf4\xf5\xf6\xf7\xf8\xf9\xfa\xff\xda\x00\x0c\x03\x01\x00\x02\x11\x03\x11\x00?\x00\xfe (\xa2\x8a\x00(\xa2\x8a\x00(\xa2\x8a\x00(\xa2\x8a\x00(\xa2\x8a\x00(\xa2\x8a\x00(\xa2\x8a\x00(\xa2\x8a\x00(\xa2\x8a\x00(\xa2\x8a\x00(\xa2\x8a\x00(\xa2\x8a\x00(\xa2\x8a\x00(\xa2\x8a\x00(\xa2\x8a\x00(\xa2\x8a\x00(\xa2\x8a\x00(\xa2\x8a\x00(\xa2\x8a\x00(\xa2\x8a\x00(\xa2\x8a\x00(\xa2\x8a\x00(\xa2\x8a\x00(\xa2\x8a\x00(\xa2\x8a\x00(\xa2\x8a\x00(\xa2\x8a\x00(\xa2\x8a\x00(\xa2\x8a\x00(\xa2\x8a\x00(\xa2\x8a\x00(\xa2\x8a\x00(\xa2\x8a\x00(\xa2\x8a\x00(\xa2\x9cJ\xe1p\xac\x08\\1\xdc\x08-\xb8\x90\xc0m\x18\x1b\n\xae\xdc\x92X\x16\xdd\x83\xb4\x1d\xb4\xff\x00\x81\xe6\xff\x00-/\xbfk\xb4\xd2MI\xb9%et\x9f5\xe6\xf9\xa2\xb9ch\xb4\x9aM\xcb\xdeq\x8f,e\xefsr\xc6[\x16\xbe\x1b\xf1\x15\xf6\x97{\xaeYh:\xd5\xe6\x8b\xa6\xc3sq\xa8\xeb\x16\xbaU\xf5\xc6\x95aoey\xa1i\xd7\x93\xde\xea\x10\xc0\xf6\x96\xb0\xdaj\x1e)\xf0\xc5\x8d\xcc\xb3\xcd\x1aAy\xe2=\x06\xd6VI\xf5\x8d9.1A\x07\x90r=\xbf:\xb1\x1c\xfeH\x97\xcb\\\x19\xa06\xd2\t<\xb9\xa3\x92\t#\xdbp\x92E$E[|\xa29\xe1n\x1a\xdaX\xa3\x96#\xe7\xc7\x0c\xd1\xf4Z\xdf\x8d|W\xe2v\xd5.\xbcO\xaf]\xf8\x9fT\xd5\xad\xbc5\xa7\xdd\xeb\x9e\'\xf2\xfcG\xe2\x81\xa7xGM\x8fG\xf0\xe6\x9da\xe2}n\x1dC^\xd2\xf4\xad\'H\xb4\xd3\xf4t\xd2\xf4\xedN\xce\xc2}\'L\xd14\xbb\xabK\xad;E\xd3m\xec\xa6\xf3\xe6IErky9ZW\xb2\xe5\xe5\x8f+M;\xb4\xdc\xa7\x07\x1b+)\'\xa58\xc1A>{\xd4|\xadAE\xda1\xbdE5Rm\xc6\xd5\x17-9B4\xe3R\x13\x85G\xcdV\x13\x83\x83\xe7 \xb7\x92\xe2U\x85\x0cH\xeep>\xd1qoi\x18;K\r\xf3]K\x0c1\x8c\x0f\xbd$\x8a\xb9*3\x96P`\xab\xb7\x97\x16\xb7RK4\x1at:s;\xc3\xe5\xdb\xd9\\^=\x8c1\xc7\x02\xc50X\xf5)\xf5\x1b\xe7\x96\xe6T[\x96\x91\xf5&\x8a)\x1ex\xe1\xb6H^(\xed\xeb\\\xad\xbf\x9fq\x1d\xb4\x97\x13Z\t$[y\xe7\x89m.&\xb7.\xeb\x14\x92\xc1\x05\xd5\xd0\xb5\x9d\xa2\n\xf2\xc5\x15\xdc\xe9\x0c\x8f\xb2+\xa9\xf6\xf9\x85\xa7{]4\xda\xbd\x9fM\xae\x9bM\xc6\xea\xf6\xd2N\xfa\xd9\xb4\xaeKVn\xcd4\x9d\xae\xaf\xae\xfa\xa5+J\xce\xddb\x9a\xd2\xf6m":)\x07 g\xae\x01\xe8W\xaf\xfb\'\x95\xfa\x1eGCK\xeb\xc69\xfc\xfd\xff\x00\xfdt\xc4\x14QV&\xb9\x92x\xadau\xb7T\xb3\x8aH\xa20\xdaZ\xdb\xca\xe9,\xf2\xdc\xb1\xba\x9e\x08c\x9e\xfaQ$\xce\xb1\xcd{%\xc4\xd1@"\xb5\x8aD\xb5\x82\x18c\x00\xafN\xda\xdbw\xedm\xbf\xde\xc1\xdb\xf7\x99:\xf4\xfb\xe8\xeb\xd7\xef+/U &x+\xc6\t\x07;Ww\x00\x81\x86\xc6\xe0\x0e\xe3\x95\x04+\x10\xa5\x81*\xb8J\x00(\xa2\x8a\x00(\xa2\x8a\x00(\xa2\x8a\x00(\xa2\x8a\x00(\xa2\x8a\x00(\xa2\x8a\x00s\xbb\xc8C;3\x90\xa8\x80\xb1$\x84\x8d\x168\xd7\'\xf8R5TQ\xd1UB\x8e\x00\xa6\xd1J\x0e9\xc0<\x11\xf3*\xb62\x08$n\x07\r\x82p\xc3\x0c:\x82\r\x00%\x14Q@\x0f\x90\xc6X\x18\x91\xd1vF\x08\x92E\x95\x8c\x824\x138e\x8a \x12I\x83\xc9\x1c{\x0bC\x1b$M,\xec\x86i\x19E\x14\x00QV\xde\xfe\xfaK\x1bm2K\xdb\xb94\xdb;\xbb\xdb\xfbM9\xeefk\x1b[\xedJ\x1b\x0b}F\xf6\xda\xd1\x9c\xdb\xc1w\x7fo\xa5ip^\xdc\xc5\x1a\xcdu\x0e\x9ba\x14\xef"Y\xdb\xacu(\x00\xa2\x8a(\x00\xa2\x8a(\x00\xa2\x8a(\x00\xa2\x8a(\x00\xa2\x8a(\x00\xa2\x8a(\x00\xa2\x8a(\x00\xa2\x8a(\x00\xa2\x8a(\x00\xa2\x8a(\x00\xa2\x8a(\x00\xa2\x8a(\x00\xa2\x8a(\x00\xa2\x8a(\x00\xa2\x8a(\x00\xa2\x8a(\x00\xa2\x8a(\x00\xa2\x8a(\x00\xa2\x8a(\x00\xa2\x8a(\x00\xa2\x8a(\x00\xa2\x8a(\x00\xa2\x8a(\x00\xa2\x8a(\x00\xa2\x8a(\x00\xa2\x8a(\x00\xa2\x8a(\x00\xa2\x8a(\x02\xc3C\x1a\xda\xc3p.\xed\x9eYn.a{\x15[\xbf\xb5\xdbG\x04v\x8f\x1d\xdc\xec\xf6\xa9bm\xafZ\xe6XmV\xda\xf6\xe2\xede\xb0\xbc7\xb6\xb6p\xb5\x84\xd7\xda\x1al:\x04\xb6^!\x93X\xd4\xb5\x8b\x1dF\xdbH\x82o\nZ\xe9\x9a\x1d\x96\xade\xac\xeb\xcd\xaf\xe8v\xf7:o\x88o\xee\xbcC\xa2\xcf\xe1\x9d"/\x0b\xcf\xe2Mb\roM\xd3|]{q\xaf\xe9Z\x1f\x86\xe4\xf0\xfd\xae\x9d\xe2\x0b\xff\x00\x15\xf8g\x1e\x8a\x00\xda\xd0g\xf0\xf5\xbd\xf4\xf2x\x9fK\xd6\xb5\x8d5\xb4o\x11\xc1mi\xa0\xeb\xd6>\x1b\xbe\x8b\xc47^\x1e\xd5-\xbc#\xaaO\xa8\xea>\x1b\xf1U\xbd\xc6\x8d\xa1\xf8\xb2m\x17Z\xf1&\x83\x1e\x97m}\xe2\xaf\x0e\xe9\xfa\xa7\x85\xf4\xcf\x12x7R\xd6-<_\xa1\xe4F\xc1$\x8d\xda4\x95Q\xd1\xda)\x0b\x88\xe5U`\xcd\x14\x86\'\x8eP\x92\x00Q\xccRG V&9\x11\xf0\xc1\x94P\x07\xff\xd9'

## Extracting metadata to dataframe

In [17]:
def parse_ifd_ratio(value):
    """
    Converts exifread IfdTag (DJI-safe) to float
    """
    try:
        v = value.values

        # Case: single Ratio like 465147/1000
        if hasattr(v, "num") and hasattr(v, "den"):
            return float(v.num) / float(v.den)

        # Case: list containing Ratio
        if isinstance(v, (list, tuple)):
            first = v[0]

            if hasattr(first, "num") and hasattr(first, "den"):
                return float(first.num) / float(first.den)

            return float(first)

        return float(v)

    except Exception:
        return None

In [18]:
def get_gps_exifread(image_path):
    with open(image_path, 'rb') as f:
        tags = exifread.process_file(f, details=False)

    lat = lon = alt = None

    try:
        lat_ref = tags.get("GPS GPSLatitudeRef")
        lat_val = tags.get("GPS GPSLatitude")
        lon_ref = tags.get("GPS GPSLongitudeRef")
        lon_val = tags.get("GPS GPSLongitude")

        alt_ref = tags.get("GPS GPSAltitudeRef")
        alt_val = tags.get("GPS GPSAltitude")

        # ---- LAT/LON ----
        def to_deg(v):
            d, m, s = v.values
            return (
                float(d.num / d.den) +
                float(m.num / m.den) / 60 +
                float(s.num / s.den) / 3600
            )

        if lat_val and lon_val:
            lat = to_deg(lat_val)
            lon = to_deg(lon_val)

            if lat_ref.values != "N":
                lat = -lat
            if lon_ref.values != "E":
                lon = -lon

        # ---- ALTITUDE (NOW FIXED) ----
        if alt_val:
            alt = parse_ifd_ratio(alt_val)

            if alt_ref.values == 1:
                alt = -alt

    except Exception as e:
        print("ERROR:", e)

    return lat, lon, alt

In [19]:
rows = []

for root, _, files in os.walk("./dataset/PAPI_06"):
    for file in files:
        if file.lower().endswith((".jpg", ".jpeg")):
            path = os.path.join(root, file)

            lat, lon, alt = get_gps_exifread(path)

            rows.append({
                "file": file,
                "path": path,
                "latitude": lat,
                "longitude": lon,
                "altitude": alt
            })

df_PAPI_06_metadata = pd.DataFrame(rows)
df_PAPI_06_metadata.head()

,file,path,latitude,longitude,altitude
0,DJI_20260429002101_0001_V.JPG,./dataset/PAPI_06\DJI_202604290007_019_300mRwy...,47.667486,9.500453,465.147
1,DJI_20260429002102_0003_V.JPG,./dataset/PAPI_06\DJI_202604290007_019_300mRwy...,47.667485,9.500453,465.143
2,DJI_20260429002102_0004_V.JPG,./dataset/PAPI_06\DJI_202604290007_019_300mRwy...,47.667486,9.500453,465.141
3,DJI_20260429002103_0005_V.JPG,./dataset/PAPI_06\DJI_202604290007_019_300mRwy...,47.667486,9.500453,465.141
4,DJI_20260429002104_0006_V.JPG,./dataset/PAPI_06\DJI_202604290007_019_300mRwy...,47.667486,9.500453,465.139

In [20]:
rows = []

for root, _, files in os.walk("./dataset/PAPI_24"):
    for file in files:
        if file.lower().endswith((".jpg", ".jpeg")):
            path = os.path.join(root, file)

            lat, lon, alt = get_gps_exifread(path)

            rows.append({
                "file": file,
                "path": path,
                "latitude": lat,
                "longitude": lon,
                "altitude": alt
            })

df_PAPI_24_metadata = pd.DataFrame(rows)
df_PAPI_24_metadata.head()

,file,path,latitude,longitude,altitude
0,DJI_20260428192656_0001_V.JPG,./dataset/PAPI_24\DJI_202604281910_010_UgCS\DJ...,47.675202,9.522888,468.034
1,DJI_20260428192657_0003_V.JPG,./dataset/PAPI_24\DJI_202604281910_010_UgCS\DJ...,47.675202,9.522888,468.035
2,DJI_20260428192657_0004_V.JPG,./dataset/PAPI_24\DJI_202604281910_010_UgCS\DJ...,47.675202,9.522888,468.054
3,DJI_20260428192658_0005_V.JPG,./dataset/PAPI_24\DJI_202604281910_010_UgCS\DJ...,47.675202,9.522888,468.094
4,DJI_20260428192658_0006_V.JPG,./dataset/PAPI_24\DJI_202604281910_010_UgCS\DJ...,47.675202,9.522888,468.145

In [21]:
PAPI_06_Height = min(df_PAPI_06_metadata["altitude"].values)
print(f"PAPI_06 Approximate floor height: {PAPI_06_Height}")
PAPI_24_Height = min(df_PAPI_24_metadata["altitude"].values)
print(f"PAPI_24 Approximate floor height: {PAPI_24_Height}")

PAPI_06 Approximate floor height: 464.988
PAPI_24 Approximate floor height: 467.609

In [22]:
PAPI_06_df["altitude"] = PAPI_06_Height
PAPI_24_df["altitude"] = PAPI_24_Height
PAPI_06_df.head()

  Bezeichnung  Punktnummer  longitude   latitude  altitude
0     PAPI 06            1   9.504007  47.668810   464.988
1     PAPI 06            2   9.503948  47.668881   464.988
2     PAPI 06            3   9.503888  47.668951   464.988
3     PAPI 06            4   9.503828  47.669021   464.988

In [23]:
PAPI_24_df.head()

  Bezeichnung  Punktnummer  longitude   latitude  altitude
0     PAPI 24            1   9.518154  47.673521   467.609
1     PAPI 24            2   9.518214  47.673450   467.609
2     PAPI 24            3   9.518274  47.673380   467.609
3     PAPI 24            4   9.518333  47.673309   467.609

## Calculate angle to the PAPI lights

In [24]:
def haversine(lat1, lon1, lat2, lon2):
    R = 6371000  # Earth radius (m)

    phi1 = np.radians(lat1)
    phi2 = np.radians(lat2)
    dphi = np.radians(lat2 - lat1)
    dlambda = np.radians(lon2 - lon1)

    a = np.sin(dphi/2)**2 + np.cos(phi1)*np.cos(phi2)*np.sin(dlambda/2)**2
    c = 2 * np.arctan2(np.sqrt(a), np.sqrt(1-a))

    return R * c

In [25]:
def compute_angles(drone_row, light_row):
    dist = haversine(
        drone_row["latitude"],
        drone_row["longitude"],
        light_row["latitude"],
        light_row["longitude"]
    )

    dh = drone_row["altitude"] - light_row["altitude"]

    elevation = np.degrees(np.arctan2(dh, dist)) if dist != 0 else 0

    return dist, elevation

In [26]:
rows = []

for _, drone in df_PAPI_06_metadata.iterrows():
    for _, light in PAPI_06_df.iterrows():

        dist, elev = compute_angles(drone, light)

        rows.append({
            "image": drone["file"],
            "drone_lat": drone["latitude"],
            "drone_lon": drone["longitude"],
            "drone_alt": drone["altitude"],
            "light_lat": light["latitude"],
            "light_lon": light["longitude"],
            "light_alt": light["altitude"],
            "distance_m": dist,
            "elevation_angle_deg": elev
        })

df_angles = pd.DataFrame(rows)
df_angles.head()

,image,drone_lat,drone_lon,drone_alt,light_lat,light_lon,light_alt,distance_m,elevation_angle_deg
0,DJI_20260429002101_0001_V.JPG,47.667486,9.500453,465.147,47.668810,9.504007,464.988,304.148348,0.029953
1,DJI_20260429002101_0001_V.JPG,47.667486,9.500453,465.147,47.668881,9.503948,464.988,304.240058,0.029944
2,DJI_20260429002101_0001_V.JPG,47.667486,9.500453,465.147,47.668951,9.503888,464.988,304.477806,0.029920
3,DJI_20260429002101_0001_V.JPG,47.667486,9.500453,465.147,47.669021,9.503828,464.988,304.980333,0.029871
4,DJI_20260429002102_0003_V.JPG,47.667485,9.500453,465.143,47.668810,9.504007,464.988,304.153159,0.029199

In [28]:
print(max(df_angles["elevation_angle_deg"].values))
print(min(df_angles["elevation_angle_deg"].values))

2.850852112838877
0.0

## Full Dataset folder merging and analysis

In [ ]:
# =========================================================
# INPUT / OUTPUT
# =========================================================

SOURCE_ROOT = "PAPI_Full"
OUTPUT_ROOT = "PAPI_Merged"

OUTPUT_IMAGES = os.path.join(OUTPUT_ROOT, "images")
OUTPUT_LABELS = os.path.join(OUTPUT_ROOT, "labels")

os.makedirs(OUTPUT_IMAGES, exist_ok=True)
os.makedirs(OUTPUT_LABELS, exist_ok=True)

# =========================================================
# VALID IMAGE EXTENSIONS
# =========================================================

IMAGE_EXTENSIONS = (".jpg", ".jpeg", ".png")

# =========================================================
# COUNTERS
# =========================================================

image_count = 0
label_count = 0

# =========================================================
# WALK THROUGH ENTIRE DATASET
# =========================================================

for root, dirs, files in os.walk(SOURCE_ROOT):

    # -----------------------------------------------------
    # MERGE IMAGES
    # -----------------------------------------------------

    if os.path.basename(root).lower() == "images":

        for file in files:

            if not file.lower().endswith(IMAGE_EXTENSIONS):
                continue

            src_path = os.path.join(root, file)

            # Create unique filename
            parent_folder = os.path.basename(os.path.dirname(root))
            new_name = f"{parent_folder}_{file}"

            dst_path = os.path.join(OUTPUT_IMAGES, new_name)

            shutil.copy2(src_path, dst_path)

            image_count += 1

    # -----------------------------------------------------
    # MERGE LABELS
    # -----------------------------------------------------

    if os.path.basename(root).lower() == "labels":

        for file in files:

            if not file.lower().endswith(".txt"):
                continue

            src_path = os.path.join(root, file)

            # Create matching unique filename
            parent_folder = os.path.basename(os.path.dirname(root))
            new_name = f"{parent_folder}_{file}"

            dst_path = os.path.join(OUTPUT_LABELS, new_name)

            shutil.copy2(src_path, dst_path)

            label_count += 1

# =========================================================
# DONE
# =========================================================

print(f"Copied {image_count} images")
print(f"Copied {label_count} labels")
print("Dataset merge complete.")

Copied 3194 images
Copied 3194 labels
Dataset merge complete.

## Splitting into training, testing and validation folders

In [5]:
# =========================================================
# SETTINGS
# =========================================================

SOURCE_DATASET = "PAPI_Merged"

IMAGES_DIR = os.path.join(SOURCE_DATASET, "images")
LABELS_DIR = os.path.join(SOURCE_DATASET, "labels")

OUTPUT_DATASET = "PAPI_Split"

TRAIN_RATIO = 0.70
VALID_RATIO = 0.20
TEST_RATIO  = 0.10

RANDOM_SEED = 42

# =========================================================
# CREATE OUTPUT STRUCTURE
# =========================================================

splits = ["train", "valid", "test"]

for split in splits:

    os.makedirs(
        os.path.join(OUTPUT_DATASET, split, "images"),
        exist_ok=True
    )

    os.makedirs(
        os.path.join(OUTPUT_DATASET, split, "labels"),
        exist_ok=True
    )

# =========================================================
# GET ALL IMAGES
# =========================================================

IMAGE_EXTENSIONS = (".jpg", ".jpeg", ".png")

all_images = [
    f for f in os.listdir(IMAGES_DIR)
    if f.lower().endswith(IMAGE_EXTENSIONS)
]

# Shuffle reproducibly
random.seed(RANDOM_SEED)
random.shuffle(all_images)

# =========================================================
# CALCULATE SPLITS
# =========================================================

total = len(all_images)

train_end = int(total * TRAIN_RATIO)
valid_end = train_end + int(total * VALID_RATIO)

train_files = all_images[:train_end]
valid_files = all_images[train_end:valid_end]
test_files  = all_images[valid_end:]

print(f"Total images: {total}")
print(f"Train: {len(train_files)}")
print(f"Valid: {len(valid_files)}")
print(f"Test : {len(test_files)}")

# =========================================================
# COPY FILES
# =========================================================

def copy_split(files, split_name):

    for image_file in files:

        image_src = os.path.join(IMAGES_DIR, image_file)

        label_file = image_file.rsplit(".", 1)[0] + ".txt"
        label_src = os.path.join(LABELS_DIR, label_file)

        image_dst = os.path.join(
            OUTPUT_DATASET,
            split_name,
            "images",
            image_file
        )

        label_dst = os.path.join(
            OUTPUT_DATASET,
            split_name,
            "labels",
            label_file
        )

        # Copy image
        shutil.copy2(image_src, image_dst)

        # Copy label if exists
        if os.path.exists(label_src):
            shutil.copy2(label_src, label_dst)

# =========================================================
# EXECUTE SPLITS
# =========================================================

copy_split(train_files, "train")
copy_split(valid_files, "valid")
copy_split(test_files, "test")

print("Dataset split complete.")

Total images: 3194
Train: 2235
Valid: 638
Test : 321
Dataset split complete.